---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-master
  namespace: testing-namespace
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      namespace: testing-namespace       
      labels:
        app: mongo
    spec:
      containers:
      - name: master
        image: mongo:3
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-master
  namespace: testing-namespace
spec:
  ports:
  - port: 27017
    name: "27017"
    protocol: TCP
    targetPort: 27017   
  selector:
    app: mongo
  type: ClusterIP
    