---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis-master
  namespace: testing-namespace
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      namespace: testing-namespace       
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: testing-namespace
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
    