---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog3
        image: graylog/graylog:3.2
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: secret1234567890
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 23f4d99f562bdf88d62b016cf99f0e32cc510c6f2cb567c3ff9db5639b2ee810
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://localhost:30003/
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://es6:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:300077/graylog
        ports:
        - containerPort: 9000
        - containerPort: 12201

---
apiVersion: v1
kind: Service
metadata:
  name: graylog3
spec:
  type: NodePort
  selector:
    app: graylog
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30003
  - name: "12201"
    port: 12201
    targetPort: 12201
    nodePort: 30004
