---
apiVersion: networking.k8s.io/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017

# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
# spec:
#   selector:
#     service: mongodb
#   ports:
#   - name: "27017"
#     port: 27017
#     targetPort: 27017
