apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    owner: pls
  name: pls-hello-world-v2
  namespace: default
spec:
  ports:
  - nodePort: 30369
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
    owner: pls
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    owner: pls
  name: pls-hello-world-v2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-world
      owner: pls
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
        owner: pls
    spec:
      containers:
      - image: nginx:1.9.1
        imagePullPolicy: Always
        name: hello-world
