---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yml
- service.yml

commonLabels:
  owner: pls
  
nameSuffix: -v2  
namePrefix: pls-

images:  
- name: nginx
  newTag: 1.9.1