kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "wordpresschart.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpresschart.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ template "wordpresschart.fullname" . }}-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: baza
            - name: MYSQL_USER
              value: pablo
            - name: MYSQL_PASSWORD
              value: pablo

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "wordpresschart.fullname" . }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpresschart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ template "wordpresschart.fullname" . }}-app
    spec:
      containers:
        - name: wordpress-app
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ template "wordpresschart.fullname" . }}-db-service.default.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: pablo
            - name: WORDPRESS_DB_PASSWORD
              value: pablo
            - name: WORDPRESS_DB_NAME
              value: baza

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "wordpresschart.fullname" . }}-db-service
spec:
  type: NodePort
  selector:
    app: {{ template "wordpresschart.fullname" . }}-db
  ports:
    - port: 3306
      targetPort: 3306

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "wordpresschart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "wordpresschart.fullname" . }}-app
  ports:
    - port: 80
      targetPort: 80