apiVersion: apps/v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: ubuntu
    command: ['sleep']
    args: ['60']
    volumeMounts:
    - name: secret-vol
      mountPath: "/opt/secrets"
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: pablo-secret 
