kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "mychart.fullname" . }}-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: {{ template "mychart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ template "mychart.fullname" . }}-app
    spec:
      containers:
        - name: hello-app
          image:  tutum/hello-world

---

kind: Service
apiVersion: v1
metadata:
  name: {{ template "mychart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "mychart.fullname" . }}-app
  ports:
    - port: 80
      targetPort: 80